# ymlのバージョン

version: '3'

services:
    mysql:
        image: mysql
        ports:
            - "3306:3306" # <-これがないと外からアクセス出来ない
        expose:
            - 3306
        environment:
            MYSQL_ROOT_PASSWORD: Password_01
            MYSQL_DATABASE: go_sample
            MYSQL_USER: user1
            MYSQL_PASSWORD: Password_01